### ISSUE TITLE
TODO: Tasks

### ISSUE THREAD

**Issue by glossawy** [Women-in-Computing-at-RIT/Nearables-BRICK-WebClient#7]
- [ ] QR Code Tasks
- [ ] Location Aware Tasks
- [ ] Special Event Tasks
- [ ] Networking Tasks
